# ======= NumPy Array =======

In [1]:
import numpy as np

arr = np.array([5,9,12,11])


print(arr)
print(type(arr))
print(arr.shape)


[ 5  9 12 11]
<class 'numpy.ndarray'>
(4,)


## ---------------- Operaters with NumPy ----------------

In [2]:
import numpy as np

arr_1 = np.array([5,9,12,11])
arr_2 = np.array([3,9,4,8])

sum_arr = arr_1 + arr_2
dic_arr = arr_1 - arr_2
mul_arr = arr_1 * arr_2
div_arr = arr_1 / arr_2
divi_arr = arr_1 // arr_2
di_arr = arr_1 % arr_2

print(sum_arr)
print(dic_arr)
print(mul_arr)
print(div_arr)
print(divi_arr)
print(di_arr)


[ 8 18 16 19]
[2 0 8 3]
[15 81 48 88]
[1.66666667 1.         3.         1.375     ]
[1 1 3 1]
[2 0 0 3]


## ---------------- NumPy pre defined methods ----------------

In [3]:
import numpy as np

arr = np.array([16,9,25,64])

# ---------------- sqrt( ) ----------------
sqrt_arr = np.sqrt(arr)
print(sqrt_arr)

# ---------------- max( ) ----------------
max_value = np.max(arr)
print(max_value)

# ---------------- min( ) ----------------
min_value = np.min(arr)
print(min_value)

# ---------------- sum( ) ----------------
sum_value = np.sum(arr)
print(sum_value)

# ---------------- mean( ) ----------------
mean_value = np.mean(arr)
print(mean_value)



[4. 3. 5. 8.]
64
9
114
28.5


## ---------------- 2D Array ----------------

In [4]:
import numpy as np

arr_2d = np.array([[6,8,10],[7,5,8],[7,5,8],[7,5,8]])

print(arr_2d)

#------------ (4, 3) ------------
print(arr_2d.shape)
#------------ 2 ------------
print(arr_2d.ndim)
#------------ 12 ------------
print(arr_2d.size)

[[ 6  8 10]
 [ 7  5  8]
 [ 7  5  8]
 [ 7  5  8]]
(4, 3)
2
12


In [5]:
# ----------------- Q1 -----------------

import numpy as np

quize_arr = np.array([ 
    [[1,2],[1,2],[1,2]], 
    [[1,2],[1,2],[1,2]], 
    [[1,2],[1,2],[1,2]], 
    [[1,2],[1,2],[1,2]] 
])

print(quize_arr)
print()
print('Shape ->' , quize_arr.shape)
print('Diamantion ->' ,quize_arr.ndim)
print('Values Count ->' ,quize_arr.size)

[[[1 2]
  [1 2]
  [1 2]]

 [[1 2]
  [1 2]
  [1 2]]

 [[1 2]
  [1 2]
  [1 2]]

 [[1 2]
  [1 2]
  [1 2]]]

Shape -> (4, 3, 2)
Diamantion -> 3
Values Count -> 24


## ---------------- 3D Array ----------------

In [6]:
import numpy as np

arr_3d = np.array([
    [[6,8,10],[7,5,8]],
    [[6,8,10],[7,5,8]]
])

print('Shape ->' , arr_3d.shape)
print(arr_3d.ndim)

Shape -> (2, 2, 3)
3


In [7]:
import numpy as np

arr_2d = np.array([[6,8,10],[7,5,8],[7,5,8],[7,5,8]])

print(arr_2d)
print()
print(arr_2d[0, 2])

[[ 6  8 10]
 [ 7  5  8]
 [ 7  5  8]
 [ 7  5  8]]

10


## ---------------- filtered_arr ----------------

In [8]:
import numpy as np

arr = np.array([16,9,25,64])

condition = arr > 18
print(condition)

filtered_arr = arr[condition]
print(filtered_arr)

[False False  True  True]
[25 64]


In [9]:
# ----------------- Q2 -----------------

import numpy as np

arr = np.array([12,18,22,19,30])

condition = (arr > 15) & (arr < 20) 

filtered_arr = arr[condition]
print(filtered_arr)

[18 19]


In [10]:
# ----------------- Q3 -----------------

import numpy as np

arr = np.array([
    [12, 5, 7, 20],
    [3, 15, 8, 2],
    [10, 25, 6, 18],
    [4, 11, 30, 9],
])

condition = ((arr > 10) | (arr < 5)) & (arr != 15)


print(arr[ condition ])

[12 20  3  2 25 18  4 11 30]


## ========= Array Initialize =========

## ------------ np.zeros( shape ) ------------

In [11]:
import numpy as np

arr = np.zeros((3,4))

print(arr)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## ------------ np.full( shape, value ) ------------

In [12]:

arr = np.full( (2,3), 5)

print(arr)

[[5 5 5]
 [5 5 5]]


## ------------ np.empty( shape ) ------------

In [13]:

arr = np.empty( (2,3) )

print(arr)

[[0.00000000e+000 8.90104239e-307 1.11255866e-306]
 [1.33511561e-306 1.11261027e-306 4.94065646e-322]]


# ======= Pandas =======

In [14]:
import pandas as pd

data = {
    'Name': ['Tharu', 'Anju', 'Sachi'],
    'Age': [21, 22, 20],
}

df = pd.DataFrame(data)

print(df)
print("------------------")

# ------------------------------------- Useing Lable -------------------------------------

print(df.loc[1]) # mehidi row lable use karayi
print("------------------")

print(df.loc[2,"Age"])
print("------------------")

# ------------------------------------- Index Lable -------------------------------------

print(df.iloc[1]) # mehidi row index use karayi
print("------------------")

print(df.iloc[2, 1])
print("------------------")

print(df['Age'])
print(df.Age)
print("------------------")


    Name  Age
0  Tharu   21
1   Anju   22
2  Sachi   20
------------------
Name    Anju
Age       22
Name: 1, dtype: object
------------------
20
------------------
Name    Anju
Age       22
Name: 1, dtype: object
------------------
20
------------------
0    21
1    22
2    20
Name: Age, dtype: int64
0    21
1    22
2    20
Name: Age, dtype: int64
------------------


In [15]:
data = {
    'calories': [420, 380, 390],
    'duration': [50, 40, 45]
}

df = pd.DataFrame(data, index = ['day1', 'day2', 'day3'])
print(df)

# print()
# print(df.loc['day3'])

# print()
# print(df.loc[['day1' , 'day3']])

# print()
# print(df.loc['day3','duration'])
# print(df.iloc[0 : 3])

# print()
# print(df.shape)
# print(df.size)
print(list(df.columns))

print()
arr = df.values
print(arr)
print(type(arr))

print()
print(df.iloc[-1])


      calories  duration
day1       420        50
day2       380        40
day3       390        45
['calories', 'duration']

[[420  50]
 [380  40]
 [390  45]]
<class 'numpy.ndarray'>

calories    390
duration     45
Name: day3, dtype: int64


In [16]:
data = {
    'calories': [420, 380, 390],
    'duration': [50, 40, 45]
}

df = pd.DataFrame(data, index = ['day1', 'day2', 'day3'])

# ---------------------- get row count ----------------------
print(len(df))
print(df.shape[0])
print(df.count())

print()

# ---------------------- get row count ----------------------
print(len(df.columns))
print(len(df.keys()))
print(df.shape[1])
print(df.size / len(df))

3
3
calories    3
duration    3
dtype: int64

2
2
2
2.0


In [17]:
data = {
    'calories': [420, 380, 390, 450],
    'duration': [50, 40, 45, 60]
}

df = pd.DataFrame(data)


print(df.sum())
print()
print(df.mean())
print()
print(df.describe())

calories    1640
duration     195
dtype: int64

calories    410.00
duration     48.75
dtype: float64

         calories   duration
count    4.000000   4.000000
mean   410.000000  48.750000
std     31.622777   8.539126
min    380.000000  40.000000
25%    387.500000  43.750000
50%    405.000000  47.500000
75%    427.500000  52.500000
max    450.000000  60.000000


In [18]:

import pandas as pd


# import pandas as df

df = pd.DataFrame({
    "Name": ["Ahan", "Ben", "Chethana", "Dewwmi", "Emily"],
    "Age": [21, 17, 22, 19, 24],
    "Salary": [50000, 40000, 55000, 48000, 60000],
    "City": ["Colombo", "Galle", "Kandy", "Colombo", "Galle"]

})

print(df)

print()

filtered_df =  df[ df['Age'] > 19 ]
print(filtered_df)

print()

print(df[ (df['Salary'] > 50000) & (df['Age'] > 20) ])

print()
df['Employee Id'] = [11, 12, 13, 14, 15]
print(df)

       Name  Age  Salary     City
0      Ahan   21   50000  Colombo
1       Ben   17   40000    Galle
2  Chethana   22   55000    Kandy
3    Dewwmi   19   48000  Colombo
4     Emily   24   60000    Galle

       Name  Age  Salary     City
0      Ahan   21   50000  Colombo
2  Chethana   22   55000    Kandy
4     Emily   24   60000    Galle

       Name  Age  Salary   City
2  Chethana   22   55000  Kandy
4     Emily   24   60000  Galle

       Name  Age  Salary     City  Employee Id
0      Ahan   21   50000  Colombo           11
1       Ben   17   40000    Galle           12
2  Chethana   22   55000    Kandy           13
3    Dewwmi   19   48000  Colombo           14
4     Emily   24   60000    Galle           15


In [19]:
# ---------------------------------- Q4 -------------------------------------

import pandas as pd

df = pd.DataFrame({
    "Product": ['Laptop' , 'Mouse' , 'Keyboard' , 'Monitor' , 'Headset'],
    "UnitsSold": [12, 50, 34, 20, 40],
    "Price": [120000 , 1500 , 3500 , 25000 , 6000],
    "Discount": [0.10 , 0.05 , 0.08 , 0.12 , 0.07]
})

final_price = df['Price'] - (df['Price'] * df['Discount']) 

total_revenue = final_price * df['UnitsSold']

df['FinalPrice'] = final_price
df['TotalRevenue'] = total_revenue


print(final_price)
print()
print(total_revenue)
print()
print(df)
print()
print(df[ (df['TotalRevenue'] > 500000)])
print()
print('Total Revenue of All Products ' , df['TotalRevenue'].sum())



0    108000.0
1      1425.0
2      3220.0
3     22000.0
4      5580.0
dtype: float64

0    1296000.0
1      71250.0
2     109480.0
3     440000.0
4     223200.0
dtype: float64

    Product  UnitsSold   Price  Discount  FinalPrice  TotalRevenue
0    Laptop         12  120000      0.10    108000.0     1296000.0
1     Mouse         50    1500      0.05      1425.0       71250.0
2  Keyboard         34    3500      0.08      3220.0      109480.0
3   Monitor         20   25000      0.12     22000.0      440000.0
4   Headset         40    6000      0.07      5580.0      223200.0

  Product  UnitsSold   Price  Discount  FinalPrice  TotalRevenue
0  Laptop         12  120000       0.1    108000.0     1296000.0

Total Revenue of All Products  2139930.0


In [20]:
data = {
    'Name': ['Johh', 'Kate', 'Brendon'],
    'Age': [28, 36, 30]
}

df = pd.DataFrame(data)

print(df)

user = {
    'Name' : 'Tharusha',
    'Age' : 22
}

df.loc[len(df)] = user

print()
print(df)




      Name  Age
0     Johh   28
1     Kate   36
2  Brendon   30

       Name  Age
0      Johh   28
1      Kate   36
2   Brendon   30
3  Tharusha   22


In [21]:
data = {
    "Name": ["John", "Kate", "Brendon"],
    "Age": [28, 36, 30]
}
df = pd.DataFrame(data)
print(df)
print()

print("---- Drop a coloumn ----")
new_df = df.drop('Age', axis=1)
print(new_df)
print()

print("---- Drop a row ----")
new_df = df.drop(1, axis=0)
print(new_df)

      Name  Age
0     John   28
1     Kate   36
2  Brendon   30

---- Drop a coloumn ----
      Name
0     John
1     Kate
2  Brendon

---- Drop a row ----
      Name  Age
0     John   28
2  Brendon   30


In [22]:
df = pd.read_csv('person_data.csv')

print(df)
print(type(df))

FileNotFoundError: [Errno 2] No such file or directory: 'person_data.csv'

In [ ]:
df = pd.read_json('my_json.json')

print(df)
print(type(df))

       name  age  isStudent    hobbies
0  Tharusha   22       True    reading
1  Tharusha   22       True  traveling
2  Tharusha   22       True   swimming
<class 'pandas.core.frame.DataFrame'>
